"""clean_initial_schema

Revision ID: bb67ff99b3df
Revises: 
Create Date: 2026-07-20 00:11:47.123659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bb67ff99b3df'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('districts',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('boundary', geoalchemy2.types.Geography(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('idx_districts_boundary', 'districts', ['boundary'], unique=False, postgresql_using='gist')
    op.create_table('risk_scores',
    sa.Column('entity_type', postgresql.ENUM('zone', 'person', name='risk_entity_type'), nullable=False),
    sa.Column('entity_id', sa.String(length=100), nullable=False),
    sa.Column('entity_label', sa.String(length=150), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('shap_explanation', sa.JSON(), server_default='[]', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_scores_entity_id'), 'risk_scores', ['entity_id'], unique=False)
    op.create_table('crime_forecasts',
    sa.Column('district_id', sa.UUID(), nullable=False),
    sa.Column('crime_type', postgresql.ENUM('theft', 'chain_snatching', 'burglary', 'assault', 'vehicle_theft', 'cybercrime', 'missing_person', 'robbery', 'other', name='crime_type'), nullable=False),
    sa.Column('forecast_date', sa.Date(), nullable=False),
    sa.Column('predicted_count', sa.Float(), nullable=False),
    sa.Column('lower_bound', sa.Float(), nullable=False),
    sa.Column('upper_bound', sa.Float(), nullable=False),
    sa.Column('model_version', sa.String(length=50), server_default='v1', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crime_forecasts_forecast_date'), 'crime_forecasts', ['forecast_date'], unique=False)
    op.create_table('hotspots',
    sa.Column('district_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('centroid', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('radius_m', sa.Float(), server_default='250.0', nullable=False),
    sa.Column('crime_density', sa.Integer(), server_default='0', nullable=False),
    sa.Column('time_window', sa.String(length=20), server_default='30d', nullable=False),
    sa.Column('severity', postgresql.ENUM('low', 'medium', 'high', 'critical', name='hotspot_severity'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_hotspots_centroid', 'hotspots', ['centroid'], unique=False, postgresql_using='gist')
    op.create_table('stations',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('district_id', sa.UUID(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fir_records',
    sa.Column('fir_no', sa.String(length=50), nullable=False),
    sa.Column('station_id', sa.UUID(), nullable=False),
    sa.Column('district_id', sa.UUID(), nullable=False),
    sa.Column('crime_type', postgresql.ENUM('theft', 'chain_snatching', 'burglary', 'assault', 'vehicle_theft', 'cybercrime', 'missing_person', 'robbery', 'other', name='crime_type'), nullable=False),
    sa.Column('ipc_sections', postgresql.ARRAY(sa.String(length=20)), server_default='{}', nullable=False),
    sa.Column('incident_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reported_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('address_text', sa.Text(), nullable=True),
    sa.Column('mo_description', sa.Text(), nullable=True),
    sa.Column('status', postgresql.ENUM('open', 'investigation', 'chargesheet', 'closed', name='case_status'), server_default='open', nullable=False),
    sa.Column('victim_age_bucket', sa.String(length=20), nullable=True),
    sa.Column('accused_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('weapon_used', sa.String(length=100), nullable=True),
    sa.Column('embedding', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_fir_records_location', 'fir_records', ['location'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_fir_records_crime_type'), 'fir_records', ['crime_type'], unique=False)
    op.create_index(op.f('ix_fir_records_fir_no'), 'fir_records', ['fir_no'], unique=True)
    op.create_index(op.f('ix_fir_records_incident_datetime'), 'fir_records', ['incident_datetime'], unique=False)
    op.create_index(op.f('ix_fir_records_status'), 'fir_records', ['status'], unique=False)
    op.create_table('users',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('badge_no', sa.String(length=50), nullable=False),
    sa.Column('role', postgresql.ENUM('constable', 'sho', 'sp', 'commissioner', 'analyst', 'admin', name='user_role'), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('station_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_badge_no'), 'users', ['badge_no'], unique=True)
    op.create_table('alerts',
    sa.Column('type', postgresql.ENUM('anomaly', 'forecast_spike', 'new_hotspot', 'missing_person_match', name='alert_type'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('severity', postgresql.ENUM('low', 'medium', 'high', 'critical', name='hotspot_severity'), nullable=False),
    sa.Column('target_role', sa.String(length=30), nullable=True),
    sa.Column('station_id', sa.UUID(), nullable=True),
    sa.Column('location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('acknowledged', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('acknowledged_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['acknowledged_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_alerts_location', 'alerts', ['location'], unique=False, postgresql_using='gist')
    op.create_table('audit_log',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource', sa.String(length=150), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('missing_persons',
    sa.Column('name_hash', sa.String(length=128), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('last_seen_location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('last_seen_address', sa.String(length=255), nullable=True),
    sa.Column('last_seen_date', sa.Date(), nullable=False),
    sa.Column('status', postgresql.ENUM('reported', 'active_search', 'matched', 'closed', name='missing_person_status'), server_default='reported', nullable=False),
    sa.Column('matched_fir_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['matched_fir_id'], ['fir_records.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_missing_persons_last_seen_location', 'missing_persons', ['last_seen_location'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_missing_persons_name_hash'), 'missing_persons', ['name_hash'], unique=False)
    op.create_table('reports',
    sa.Column('type', postgresql.ENUM('weekly', 'hotspot', 'case', name='report_type'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('status', postgresql.ENUM('pending', 'generating', 'ready', 'failed', name='report_status'), server_default='pending', nullable=False),
    sa.Column('requested_by', sa.UUID(), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('district_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('suspects',
    sa.Column('fir_id', sa.UUID(), nullable=False),
    sa.Column('name_hash', sa.String(length=128), nullable=False),
    sa.Column('display_label', sa.String(length=100), nullable=False),
    sa.Column('age_bucket', sa.String(length=20), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('prior_case_ids', postgresql.ARRAY(sa.String(length=50)), server_default='{}', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fir_id'], ['fir_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suspects_name_hash'), 'suspects', ['name_hash'], unique=False)
    op.create_table('vehicles',
    sa.Column('fir_id', sa.UUID(), nullable=False),
    sa.Column('vehicle_type', sa.String(length=50), nullable=False),
    sa.Column('reg_pattern_hash', sa.String(length=128), nullable=False),
    sa.Column('theft_location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('recovery_location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('status', postgresql.ENUM('stolen', 'recovered', 'under_investigation', name='vehicle_crime_status'), server_default='stolen', nullable=False),
    sa.Column('theft_date', sa.Date(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fir_id'], ['fir_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_vehicles_recovery_location', 'vehicles', ['recovery_location'], unique=False, postgresql_using='gist')
    op.create_index('idx_vehicles_theft_location', 'vehicles', ['theft_location'], unique=False, postgresql_using='gist')
    op.create_table('criminal_network_edges',
    sa.Column('suspect_a_id', sa.UUID(), nullable=False),
    sa.Column('suspect_b_id', sa.UUID(), nullable=False),
    sa.Column('relation_type', sa.String(length=50), nullable=False),
    sa.Column('weight', sa.Float(), server_default='1.0', nullable=False),
    sa.Column('source_fir_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_fir_id'], ['fir_records.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['suspect_a_id'], ['suspects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['suspect_b_id'], ['suspects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('spatial_ref_sys')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name=op.f('spatial_ref_sys_srid_check')),
    sa.PrimaryKeyConstraint('srid', name=op.f('spatial_ref_sys_pkey'))
    )
    op.drop_table('criminal_network_edges')
    op.drop_index('idx_vehicles_theft_location', table_name='vehicles', postgresql_using='gist')
    op.drop_index('idx_vehicles_recovery_location', table_name='vehicles', postgresql_using='gist')
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_suspects_name_hash'), table_name='suspects')
    op.drop_table('suspects')
    op.drop_table('reports')
    op.drop_index(op.f('ix_missing_persons_name_hash'), table_name='missing_persons')
    op.drop_index('idx_missing_persons_last_seen_location', table_name='missing_persons', postgresql_using='gist')
    op.drop_table('missing_persons')
    op.drop_table('audit_log')
    op.drop_index('idx_alerts_location', table_name='alerts', postgresql_using='gist')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_users_badge_no'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_fir_records_status'), table_name='fir_records')
    op.drop_index(op.f('ix_fir_records_incident_datetime'), table_name='fir_records')
    op.drop_index(op.f('ix_fir_records_fir_no'), table_name='fir_records')
    op.drop_index(op.f('ix_fir_records_crime_type'), table_name='fir_records')
    op.drop_index('idx_fir_records_location', table_name='fir_records', postgresql_using='gist')
    op.drop_table('fir_records')
    op.drop_table('stations')
    op.drop_index('idx_hotspots_centroid', table_name='hotspots', postgresql_using='gist')
    op.drop_table('hotspots')
    op.drop_index(op.f('ix_crime_forecasts_forecast_date'), table_name='crime_forecasts')
    op.drop_table('crime_forecasts')
    op.drop_index(op.f('ix_risk_scores_entity_id'), table_name='risk_scores')
    op.drop_table('risk_scores')
    op.drop_index('idx_districts_boundary', table_name='districts', postgresql_using='gist')
    op.drop_table('districts')
    # ### end Alembic commands ###
